name: Build and Deploy Application

on:
  push:
    branches: master
    paths:
      - '.github/**'
      - 'src/**'
      - '**.gradle'
      - 'scripts/**'
  workflow_dispatch:
env:
  BUILD_FILE_NAME: donelib.jar
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew test

      - name: Build With Gradle
        run: ./gradlew clean build
      
      - name: Set build name
        run: |
          echo "BUILD_NAME=$(date '+%Y-%m-%d-%s')_$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
      - name: Zip build file
        run: | 
          mkdir temp
          cp -r appspec.yml scripts temp
          cp build/libs/$BUILD_FILE_NAME temp/$BUILD_NAME
          zip -r server.zip temp/*

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy build file to S3
        run: aws s3 cp --region ${{ secrets.AWS_REGION }} server.zip s3://donelib-bucket/server-deploy/server.zip

      - name: Deploy with AWS codeDeploy
        run: aws deploy create-deployment
             --application-name donelib-codedeploy-application
             --deployment-config-name CodeDeployDefault.OneAtATime
             --deployment-group-name donelib-backend
             --s3-location bucket=donelib-bucket,bundleType=zip,key=server-deploy/server.zip
